### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by cesasol** [seyd/JS.Responsive#1]
Installing this library trough npm gives an error with the postinstall script
```
> JS.Responsive@3.2.0 install /Users/cesar/Builds/vue/wepack-vue/node_modules/JS.Responsive
> node server/postInstall.js

{ Error: ENOENT: no such file or directory, open '/Users/cesar/Builds/vue/wepack-vue/node_modules/JS.Responsive/server/../node_modules/ink-docstrap/template/tmpl/details.tmpl'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/cesar/Builds/vue/wepack-vue/node_modules/JS.Responsive/server/../node_modules/ink-docstrap/template/tmpl/details.tmpl' }
/Users/cesar/Builds/vue/wepack-vue/node_modules/JS.Responsive/server/postInstall.js:29
	if ( contents.match( /data\.customclass && data\.customclass\.length/ ) )
	             ^

TypeError: Cannot read property 'match' of undefined
    at ReadFileContext.callback (/Users/cesar/Builds/vue/wepack-vue/node_modules/JS.Responsive/server/postInstall.js:29:15)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/cesar/.nvm/versions/node/v6.9.5/bin/node" "/Users/cesar/.nvm/versions/node/v6.9.5/bin/npm" "install" "JS.Responsive"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! JS.Responsive@3.2.0 install: `node server/postInstall.js`
npm ERR! Exit status 1
```

**Comment by cesasol** [comment]
This was introduced in 3.0.0 version as in 2.3.4 there was no such hook. There is a reason for using this hook instead of a custom script to execute manually for building/working with this library?

**Comment by luckylooke** [comment]
Oh sorry, my fault, it seems to be not needed for common install.. If you are in a hurry, just comment out the part realted to issue in server/postInstall.js. I will check if it is still needed and will fix the error during the weekend, thanks for patience ;)

**Comment by luckylooke** [comment]
Thanks for reporting, will be in next release ;)
